# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/WebP0',
                'doc_host': 'https://Dzaposlav.github.io',
                'git_url': 'https://github.com/Dzaposlav/WebP0',
                'lib_path': 'WebP0'},
  'syms': {'WebP0.core': {'WebP0.core.foo': ('core.html#foo', 'WebP0/core.py')}}}
